const path = require('path');
const dotenv = require('dotenv');
dotenv.config({ path: path.resolve(__dirname, '../.env') });
const mongoose = require('mongoose');
const Algorithm = require('../models/Algorithm');
const Problem = require('../models/Problem');

const algorithms = [
  { name: 'Binary Search', category: 'Searching', difficulty: 'Easy', complexity: 'O(log n)', spaceComplexity: 'O(1)', description: 'Efficiently find an element in a sorted array by repeatedly halving the search interval.', tags: ['array', 'divide and conquer'], code: { javascript: `function binarySearch(arr, target) {\n  let left = 0, right = arr.length - 1;\n  while (left <= right) {\n    const mid = Math.floor((left + right) / 2);\n    if (arr[mid] === target) return mid;\n    if (arr[mid] < target) left = mid + 1;\n    else right = mid - 1;\n  }\n  return -1;\n}`, cpp: `int binarySearch(vector<int>& arr, int target) {\n  int left = 0, right = arr.size() - 1;\n  while (left <= right) {\n    int mid = left + (right - left) / 2;\n    if (arr[mid] == target) return mid;\n    if (arr[mid] < target) left = mid + 1;\n    else right = mid - 1;\n  }\n  return -1;\n}`, python: `def binary_search(arr, target):\n    left, right = 0, len(arr) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if arr[mid] == target: return mid\n        elif arr[mid] < target: left = mid + 1\n        else: right = mid - 1\n    return -1` } },
  { name: 'Merge Sort', category: 'Sorting', difficulty: 'Medium', complexity: 'O(n log n)', spaceComplexity: 'O(n)', description: 'Divide-and-conquer sorting algorithm that splits, sorts, and merges subarrays.', tags: ['sorting', 'divide and conquer', 'recursion'], code: { javascript: `function mergeSort(arr) {\n  if (arr.length <= 1) return arr;\n  const mid = Math.floor(arr.length / 2);\n  return merge(mergeSort(arr.slice(0, mid)), mergeSort(arr.slice(mid)));\n}\nfunction merge(l, r) {\n  const res = []; let i = 0, j = 0;\n  while (i < l.length && j < r.length)\n    res.push(l[i] <= r[j] ? l[i++] : r[j++]);\n  return res.concat(l.slice(i)).concat(r.slice(j));\n}`, cpp: `void merge(vector<int>& arr, int l, int m, int r) {\n  vector<int> left(arr.begin()+l, arr.begin()+m+1);\n  vector<int> right(arr.begin()+m+1, arr.begin()+r+1);\n  int i=0,j=0,k=l;\n  while(i<left.size()&&j<right.size())\n    arr[k++]=left[i]<=right[j]?left[i++]:right[j++];\n  while(i<left.size()) arr[k++]=left[i++];\n  while(j<right.size()) arr[k++]=right[j++];\n}`, python: `def merge_sort(arr):\n    if len(arr) <= 1: return arr\n    mid = len(arr) // 2\n    l, r = merge_sort(arr[:mid]), merge_sort(arr[mid:])\n    return [l.pop(0) if l and (not r or l[0]<=r[0]) else r.pop(0) for _ in range(len(l)+len(r))]` } },
  { name: "Dijkstra's Algorithm", category: 'Graph', difficulty: 'Hard', complexity: 'O((V+E) log V)', spaceComplexity: 'O(V)', description: 'Single-source shortest path on weighted graphs using a min-heap priority queue.', tags: ['graph', 'shortest path', 'greedy', 'heap'], code: { javascript: `function dijkstra(graph, start) {\n  const dist = {};\n  const pq = [[0, start]];\n  for (const n in graph) dist[n] = Infinity;\n  dist[start] = 0;\n  while (pq.length) {\n    pq.sort((a,b) => a[0]-b[0]);\n    const [d, u] = pq.shift();\n    if (d > dist[u]) continue;\n    for (const [v, w] of graph[u]||[]) {\n      if (dist[u]+w < dist[v]) {\n        dist[v] = dist[u]+w;\n        pq.push([dist[v], v]);\n      }\n    }\n  }\n  return dist;\n}`, cpp: `vector<int> dijkstra(int n, vector<vector<pair<int,int>>>& adj, int src) {\n  vector<int> dist(n, INT_MAX);\n  priority_queue<pair<int,int>, vector<pair<int,int>>, greater<>> pq;\n  dist[src]=0; pq.push({0,src});\n  while(!pq.empty()) {\n    auto [d,u]=pq.top(); pq.pop();\n    if(d>dist[u]) continue;\n    for(auto [v,w]:adj[u])\n      if(dist[u]+w<dist[v]) { dist[v]=dist[u]+w; pq.push({dist[v],v}); }\n  }\n  return dist;\n}`, python: `import heapq\ndef dijkstra(graph, start):\n    dist = {n: float('inf') for n in graph}\n    dist[start] = 0\n    pq = [(0, start)]\n    while pq:\n        d, u = heapq.heappop(pq)\n        if d > dist[u]: continue\n        for v, w in graph[u]:\n            if dist[u]+w < dist[v]:\n                dist[v] = dist[u]+w\n                heapq.heappush(pq, (dist[v], v))\n    return dist` } },
  { name: 'DFS', category: 'Graph', difficulty: 'Easy', complexity: 'O(V+E)', spaceComplexity: 'O(V)', description: 'Depth-First Search traversal exploring as far as possible before backtracking.', tags: ['graph', 'traversal', 'recursion'], code: { javascript: `function dfs(graph, start, visited = new Set()) {\n  visited.add(start);\n  for (const neighbor of graph[start]||[])\n    if (!visited.has(neighbor)) dfs(graph, neighbor, visited);\n  return visited;\n}`, cpp: `void dfs(int u, vector<vector<int>>& adj, vector<bool>& vis) {\n  vis[u] = true;\n  for (int v : adj[u])\n    if (!vis[v]) dfs(v, adj, vis);\n}`, python: `def dfs(graph, start, visited=None):\n    if visited is None: visited = set()\n    visited.add(start)\n    for neighbor in graph.get(start, []):\n        if neighbor not in visited:\n            dfs(graph, neighbor, visited)\n    return visited` } },
  { name: 'BFS', category: 'Graph', difficulty: 'Easy', complexity: 'O(V+E)', spaceComplexity: 'O(V)', description: 'Breadth-First Search traversal ideal for finding shortest paths in unweighted graphs.', tags: ['graph', 'traversal', 'queue', 'shortest path'], code: { javascript: `function bfs(graph, start) {\n  const visited = new Set([start]);\n  const queue = [start];\n  while (queue.length) {\n    const node = queue.shift();\n    for (const n of graph[node]||[])\n      if (!visited.has(n)) { visited.add(n); queue.push(n); }\n  }\n  return visited;\n}`, cpp: `void bfs(int start, vector<vector<int>>& adj, int n) {\n  vector<bool> vis(n, false);\n  queue<int> q;\n  vis[start]=true; q.push(start);\n  while(!q.empty()) {\n    int u=q.front(); q.pop();\n    for(int v:adj[u]) if(!vis[v]) { vis[v]=true; q.push(v); }\n  }\n}`, python: `from collections import deque\ndef bfs(graph, start):\n    visited = {start}\n    queue = deque([start])\n    while queue:\n        node = queue.popleft()\n        for neighbor in graph.get(node, []):\n            if neighbor not in visited:\n                visited.add(neighbor)\n                queue.append(neighbor)\n    return visited` } },
  { name: 'KMP String Search', category: 'String', difficulty: 'Hard', complexity: 'O(n+m)', spaceComplexity: 'O(m)', description: 'Knuth-Morris-Pratt linear-time pattern matching using a failure function to avoid redundant comparisons.', tags: ['string', 'pattern matching'], code: { javascript: `function kmp(text, pattern) {\n  const lps = buildLPS(pattern);\n  const res = []; let i=0,j=0;\n  while (i < text.length) {\n    if (text[i]===pattern[j]) { i++; j++; }\n    if (j===pattern.length) { res.push(i-j); j=lps[j-1]; }\n    else if (i<text.length && text[i]!==pattern[j])\n      j ? j=lps[j-1] : i++;\n  }\n  return res;\n}\nfunction buildLPS(p) {\n  const lps=[0]; let len=0,i=1;\n  while(i<p.length) {\n    if(p[i]===p[len]) lps[i++]=++len;\n    else len ? len=lps[len-1] : lps[i++]=0;\n  }\n  return lps;\n}`, cpp: ``, python: `` } },
];

const problems = [
  { title: 'Two Sum', platform: 'LeetCode', difficulty: 'Easy', tags: ['Array', 'Hash Map'], link: 'https://leetcode.com/problems/two-sum/', acceptanceRate: 49 },
  { title: 'Longest Palindromic Substring', platform: 'LeetCode', difficulty: 'Medium', tags: ['String', 'DP'], link: 'https://leetcode.com/problems/longest-palindromic-substring/', acceptanceRate: 32 },
  { title: 'Trapping Rain Water', platform: 'LeetCode', difficulty: 'Hard', tags: ['Array', 'Stack', 'Two Pointers'], link: 'https://leetcode.com/problems/trapping-rain-water/', acceptanceRate: 58 },
  { title: 'Number of Islands', platform: 'LeetCode', difficulty: 'Medium', tags: ['Graph', 'BFS', 'DFS'], link: 'https://leetcode.com/problems/number-of-islands/', acceptanceRate: 56 },
  { title: 'Coin Change', platform: 'LeetCode', difficulty: 'Medium', tags: ['DP', 'BFS'], link: 'https://leetcode.com/problems/coin-change/', acceptanceRate: 41 },
  { title: 'Word Ladder', platform: 'LeetCode', difficulty: 'Hard', tags: ['BFS', 'String'], link: 'https://leetcode.com/problems/word-ladder/', acceptanceRate: 37 },
  { title: 'Maximum Subarray', platform: 'LeetCode', difficulty: 'Medium', tags: ['Array', 'DP', 'Divide and Conquer'], link: 'https://leetcode.com/problems/maximum-subarray/', acceptanceRate: 49 },
  { title: 'Binary Tree Level Order Traversal', platform: 'LeetCode', difficulty: 'Medium', tags: ['Tree', 'BFS'], link: 'https://leetcode.com/problems/binary-tree-level-order-traversal/', acceptanceRate: 65 },
  { title: 'Merge Intervals', platform: 'LeetCode', difficulty: 'Medium', tags: ['Array', 'Sorting'], link: 'https://leetcode.com/problems/merge-intervals/', acceptanceRate: 46 },
  { title: 'Valid Parentheses', platform: 'LeetCode', difficulty: 'Easy', tags: ['Stack', 'String'], link: 'https://leetcode.com/problems/valid-parentheses/', acceptanceRate: 40 },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('Connected to MongoDB');
    await Algorithm.deleteMany({});
    await Problem.deleteMany({});
    await Algorithm.insertMany(algorithms);
    await Problem.insertMany(problems);
    console.log(`Seeded ${algorithms.length} algorithms and ${problems.length} problems`);
    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err.message);
    process.exit(1);
  }
}

seed();